[
  ./core/common.nix
  ./core/licensing.nix
  ./core/tests.nix
  ./core/lazy-packages.nix
  ./hardware/gamecontroller.nix
  ./hardware/rtl8192cu
  ./hardware/thinkpad.nix
  ./hardware/tolino.nix
  ./hardware/tuxedo-pulse1502
  ./profiles/tvl.nix
  ./programs/gnupg
  ./programs/fish/fasd.nix
  ./programs/foot/default.nix
  ./services/drawpile.nix
  ./services/postfix
  ./services/starbound.nix
  ./services/guix.nix
  ./services/upower-minimal.nix
  ./system/iso.nix
  ./system/kernel/rckernel.nix
  ./system/kernel/zswap.nix
  ./user/aszlig/profiles/base.nix
  ./user/aszlig/profiles/workstation
  ./user/aszlig/programs/flameshot
  ./user/aszlig/programs/git
  ./user/aszlig/programs/mpv
  ./user/aszlig/programs/zsh
  ./user/aszlig/services/i3
  ./user/aszlig/services/vlock
  ./user/devhell/profiles/base.nix
  ./user/devhell/profiles/packages.nix
  ./user/devhell/profiles/services.nix
  ./user/sternenseemann/services/sway.nix
  ./user/sternenseemann/services/mako
  ./user/sternenseemann/profiles/desktop.nix
  ./user/sternenseemann/profiles/editors.nix
  ./user/sternenseemann/programs/ma.nix
  ./user/sternenseemann/programs/saneterm.nix
]
