[
  ./hardware/gamecontroller.nix
  ./hardware/t100ha
  ./profiles/common.nix
  ./profiles/tests.nix
  ./services/multipath-vpn.nix
  ./services/postfix
  ./system/iso.nix
  ./system/thinkpad.nix
  ./user/aszlig/profiles/base.nix
  ./user/aszlig/profiles/workstation
  ./user/aszlig/programs/gajim
  ./user/aszlig/programs/git
  ./user/aszlig/programs/mpv
  ./user/aszlig/programs/taalo-build
  ./user/aszlig/programs/taskwarrior
  ./user/aszlig/programs/vim
  ./user/aszlig/programs/xpdf
  ./user/aszlig/programs/zsh
  ./user/aszlig/services/i3
  ./user/aszlig/services/slim
  ./user/aszlig/services/vlock
  ./user/aszlig/system/kernel.nix
  ./user/profpatsch/programs/scanning.nix
]
