# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "firewire_ohci" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/754fd3e3-2e04-4028-9363-0c6bb4c54367";
      fsType = "ext4";
    };

  hardware.trackpoint.emulateWheel = true;

  swapDevices = [ ];

  nix.maxJobs = 2;
  networking.enableIntel3945ABGFirmware = true;
}
