function appendTalkies(append_to_element) {
    talkies = [
        { talk: "Oh the things you’ll see …" },
        { talk: "I’ll manage." },
        { talk: "Spurdo Spärde sprölölö",
        hover: "bydon xDDDD" },
        { talk: "Where is Jessica Hyde?" },
        { talk: "Wie talkst du eigentlich?",
        hover: "Du Splasher" },
        { talk: "See you Space Cowboy",
        hover: "bang",
        link: "https://www.youtube.com/watch?v=DU-7SVG6mHk" },
        { talk: "STACKENBLOCKEN",
        hover: "21:45",
        link: "https://www.youtube.com/watch?v=d6wd78jMHDk" },
        { talk: "Don’t lose your waaaaaaay",
        hover: "I haven’t actually seen KlK …" },
        { talk: "STOP RIGHT THERE CRIMINAL SCUM",
        hover: "Let me tell you a story about my past …" },
        { talk: "Ich zähl bis zehn und mach die Augen wieder auf",
        hover: "Rivo Drei – Von Vorne" },
        { talk: "It’s so ironic when your makeup runs",
        hover: "blackest_eyes& trains& sound_of_muzak& prodigal" },
        { talk: "It’s time now, my time now. Give me my, give me my wings",
        hover: "Should you see your Maker’s face tonight // Look ’em in the eye, look ’em in the eye // And tell ’em // Never lived a lie, never took a life // But surely saved one // Hallelluja // It’s time for you to bring me home",
        link: "https://www.youtube.com/watch?v=7Ajx-ABtbVM"
        },
        { talk: "{-# LANGUAGE ImplicitProtolude #-}" },
        { talk: "overfull hbox" },
        { talk: "Magenta – Chartreuse",
        hover: "best colors"
        },
        { talk: "I’m still in a dream, Snake Eater" },
        { talk: "Just like a wolf in sheepskin // She had a lion’s attitude",
        link: "https://www.youtube.com/watch?v=NzPXQkByr-8" },
        { talk: "Oh Sherlock … what do we say about coincidences? – The universe is rarely so lazy",
        hover: "Manu Vaivasvata gilt als erster Herrscher der Menschen, während sein Bruder Yama der Herrscher über die Toten ist. Manu zog den Fisch Matsya auf, ein Avatar des Gottes Vishnu. Als Matsya riesig geworden war, warnte er Manu vor einer bestehenden Sintflut und riet ihm, ein Schiff zu bauen. Während der Flut ertranken alle Lebewesen, Matsya aber zog das Schiff mit Manu und den sieben Weisen zum Himalaya. Von dieser Flutsage gibt es unterschiedliche Versionen, eine davon findet sich im indischen Nationalepos Mahabharata.\nIn der rekonstruierten indoeuropäischen Mythologie ist *Monus der erste Mensch. Der im iranischen Avesta überlieferte Mannesnamen Manus-čiθra weist darauf hin, dass dieser mythische Urmensch indoiranischen Ursprungs ist.[2] Für die Germanen ist der Urmensch Mannus bezeugt. Nicht sicher ist, ob der phrygische Manes ebenfalls hierhergestellt werden darf.\nhttps://de.wikipedia.org/wiki/Manu_(Hinduismus)" },
        { talk: "Hintersicht ist zwanzigzwanzig" },
        { talk: "Under peruvian skies // Vanessa regretfully waits",
        hover: "poor Vanessa",
        link: "https://www.youtube.com/watch?v=dr0ebtzSeWM" },
        { talk: "Mir ist vor Lachen das Strickzeug in den Vodka gefallen",
        link: "https://twitter.com/architekteuse/status/829428805626429444" },
        { talk: "with every sob, her hands transform, ripples of feather flowing and receding, fingers contorting into talons. you hold them as they tear you",
        link: "https://twitter.com/ctrlcreep/status/860530414674489344" },
        { talk: "Code is code, data is data",
        hover: "If you see code as data, you get what you get" },
        { talk: "In my Raspberry Heaven",
        link: "https://www.youtube.com/watch?v=0fURptoIE2s" },
        { talk: "Just a girl and her will to survive" },
        { talk: "The first time is happenstance. The second time is coincidence. The third time is enemy action.",
        hover: "Auric Goldfinger",
        link: "http://wiki.c2.com/?RuleOfThree" },
        { talk: "Internet, da ist alles super.",
        link: "http://shitopenlabsays.tumblr.com/" },
        { talk: "Source of Contravariance" },
        { talk: "Identity is far too long a name for this" },
        { talk: "May they all be—feathers",
          link: "https://www.youtube.com/watch?v=lLre0GVbJK0",
          hover: "By the telling // May they become // May the all be // feathers" },
        { talk: "skip to content" },
        { talk: "Strong Types and Strong Memes",
          link: "https://phabricator.haskell.org/macro/" },
        { talk: "It’s so funky, and it’s low volume",
          hover: "Come on, yeah.",
          link: "https://www.youtube.com/watch?v=AWBUnr0F3Zo" },
        { talk: "set -euo pipefail",
          hover: "bash blues" },
        { talk: "I disagree with your philosophy // What killed the cat’s not curiosity",
          link: "https://www.youtube.com/watch?v=NBhVSI_napk" },
        { talk: "Chillin’ in the sky so high that the birds can barely breathe",
          hover: "And if my attitude determines the altitute, my wings won’t let me down",
          link: "https://www.youtube.com/watch?v=YBD758_JOy8" },
        { talk: "Unzerfickbar, wie wenn Mario ein Stern frisst",
          link: "https://www.youtube.com/watch?v=q72IZzpluQs" },
        { talk: "Parsley, Sage, Rosemary & Thyme",
          hover: "She was once a true love of mine", },
        { talk: "Praxis für Egotherapie" },
        { talk: "pa re ci vo mu",
          link: "https://lojban.github.io/cll/18/1/" },
        { talk: "Taxonomy of Humour" },
        { talk: "Flexibility, Love & Trust",
          hover: "Here comes a thought",
          link: "https://www.youtube.com/watch?v=rds7V5Sxu-4" },
        { talk: "Cheap Borscht",
          hover: "… is a blessing for the toothless – Yiddish proverb" },
        { talk: "Soramimi Ke–ki",
          link: "https://www.youtube.com/watch?v=Vf9Lvifxwk4" },
        { talk: "Über den Sternen // leuchten die Sterne // Verde",
          hover: "Ma-Ma-Marsi",
          link: "https://www.youtube.com/watch?v=tnnfQPoQhj0" },
        { talk: "Will you love me, tomorrow",
          hover: "Macross! Macross!",
          link: "https://www.youtube.com/watch?v=ABpvJCmWA1w" },
        { talk: "She’s so . . . heavy!!",
          hover: "HEAVEEEEEEEEYYYYYYYYY",
          link: "https://www.youtube.com/watch?v=tAe2Q_LhY8g" },
        { talk: "Genre: Blues" },
        { talk: "We may just go where no one’s been",
          hover: "Whatever will be willed of me // Whatever will be willed of me",
          link: "https://www.youtube.com/watch?v=_tcW-j7KFgY" },
        { talk: "光あれ",
          hover: "Let there be light",
          link: "TODO: Maaya Sakamoto song" },
        { talk: "BLESS THIS IMMUNITY",
          hover: "TODO",
          link: "https://www.youtube.com/watch?v=q7DfQMPmJRI" },
        { talk: "Senjougahara ought to be enough",
          hover: "TODO",
          link: "TODO" },
        { talk: "Herz fünf!",
          hover: "TODO",
          link: "TODO" },
        { talk: "Tarpit of Success" },
        { talk: "Tea and Sympathy",
          hover: "Play our heart’s lament / Like an unrehearsed symphony",
          link: "TODO" },
        { talk: "Autumn on Ganymede" },
        { talk: "Thyme, ever courageous",
          link: "https://www.youtube.com/watch?v=EV6E13xODyA" },
        { talk: "Type 🌕" },
        { talk: "Unintentionally left blank" },
        { talk: "Single Source of Truth",
          link: "TODO link to the concept" },
        { talk: "NOT NULL DEFAULT NULL" },
        { talk: "Ad hominem by choice" },
        { talk: "Designated Snack Period",
          link: "TODO something something designated sleep period" },
        { talk: "doorknob, ankle, cold",
          link: "TODO put link to llama song?",
          hover: "llama, llama, duck" },
        { talk: "??[2]",
          hover: "Aha" },
        { talk: "trap 'rm -r \"$tmp\"' EXIT" },
        { talk: "👁👄👁",
          hover: "It is what it is",
          link: "https://xn--mp8hai.fm/statement" },
        { talk: "For more information please re-read",
          hover: "Whatever you do, don’t.",
          link: "https://scarfolk.blogspot.com/" },
        { talk: "Live und in Farbe" },
        { talk: "Glob Star" },
        { talk: "Varying Degrees of Lüften",
          link: "https://www.theguardian.com/world/2020/sep/30/germans-embrace-fresh-air-to-ward-off-coronavirus" },
        { talk: "Linienhafter Sicherheitstrennstreifen",
          link: "https://de.wikipedia.org/wiki/Fahrradverkehr_in_M%C3%BCnchen" },
        { talk: "pam_happy_hour.c",
          link: "www.brendangregg.com/Specials/pam_happy_hour.c" },
        { talk: "Ctrl-g Ctrl-g Ctrl-g"},
        { talk: "PROPPATCH",
          hover: "WebDAV was a mistake" },
        { talk: "sausage shaped, but lumpy",
          link: "https://en.wikipedia.org/wiki/Bristol_stool_scale" },
        { talk: "polsterboi.json.mozlz4" },
        { talk: "buffer-local when set" },
        { talk: "Jordan Peterson's broader œuvre",
          link: "https://twitter.com/bronzeswords/status/1449345260207828995" },
        { talk: "🙏 🌧 ⬇ 🌍"
        , link: "https://www.youtube.com/watch?v=QAo_Ycocl1E" },
        { talk: "Seal II"
          , link: "https://www.youtube.com/watch?v=GRMLpJ-v7vk" }
    ];
    var talkie = talkies[Math.floor(Math.random()*talkies.length)];
    var elem = null;
    var title = "";
    if (talkie.hasOwnProperty("hover")) { title = 'title="'+talkie.hover+'"'; }
    if (talkie.hasOwnProperty("link")) {
        elem = function(content, attrs) {
            return '<a href="'+talkie.link+'" '+attrs+' >'+content+'</a>';
        };
    } else {
        elem = function(content, attrs) {
            return '<span '+attrs+'>'+content+'</span>';
        };
    }
    append_to_element.innerHTML = elem(talkie.talk, title);
}
